spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;characterEncoding=UTF-8;databaseName=transportation1
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
  redis:
    host: 192.168.44.130
    port: 6379
    password: 123321

#mybatis的配置
mybatis:
  #mapper的映射路径
  mapper-locations: classpath:mapper/*.xml
  #开启驼峰命名法
  configuration:
    map-underscore-to-camel-case: true
